yarnPath: .yarn/releases/yarn-4.10.3.cjs

enableGlobalCache: false
cacheFolder: .yarn/cache
globalFolder: .yarn/global

compressionLevel: mixed

enableImmutableInstalls: false

installStatePath: .yarn/install-state.gz

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - win32
    - darwin
